# Generated by Django 3.1.5 on 2021-04-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_tour_guide_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
