# Generated by Django 3.1.5 on 2021-04-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
