# Generated by Django 3.1.5 on 2021-04-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_booking_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
