# Generated by Django 3.1.5 on 2021-04-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='Image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
