# Generated by Django 3.1.5 on 2021-04-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_packet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='AddressMap',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
